### ISSUE TITLE
Agenda Request -  Baseline Discussion on Third Parties

### ISSUE THREAD

**Issue by AramZS** [patcg/meetings#141]
## Agenda+: What do you want to discuss?

Discussing the following baseline requirements: 
- Can multiple third parties measure the same event with no restrictions?
- Can multiple third parties measure the same event with restrictions?
- Can third parties invoke the measurement API?

**Comment by AramZS** [comment]
Considering what is currently on the agenda, I'll save this for only if we have time at TPAC

**Comment by eriktaubeneck** [comment]
In advance of the Feb 29th discussion, I wanted to post some thoughts on this subject to seed the discussion. **This content is not at all definitive, please follow up in this issue and/or at the meeting with proposed changes, concerns, or any other feedback!**


## Context

The private measurement APIs discussed by the PATCG all require some type of browser interaction (e.g., calling an API) by the website (either the _source site_ or _trigger site_.) It is often the case that the website operator will decide to use a _third party service provider_ to perform these interactions on their behalf.

The proposed private measurement APIs all include some form of budgeting or rate limiting to achieve their privacy goals. This presents challenges with respect to _third parties_.


## Goals

We aim to achieve the following in our API designs, but also recognize there are trade offs to consider.



1. Top-level site owners _must_ be able to delegate usage of the measurement API to _third party service providers._
2. Top-level site owners _should_ be able to utilize multiple _third party service providers._
    1. It _may_ be reasonable to standardize an upper limit on the number of _third party service providers._
3. The utilization of multiple _third party service providers_ _must not_ result in a reduction in the privacy afforded by the API.
4. The measurement APIs _must not_ require top-level context to operate, e.g., they should be accessible within an iFrame or similarly isolated context.
    2. A site _may_ restrict access to APIs for _third party service providers_ so that only their preferred providers can use the APIs.
5. It _must not _be possible for one _third party service provider_ to actively degrade or prevent the operation of another _third party service provider_.
    3. It _may_ be possible for the top-level site to configure a state that degrades or prevents the operation of some _third party service providers_, e.g., by embedding too many providers.
6. It _must_ be possible for an embedded _third party service provider _to operate the measurement APIs without requiring the top-level site to take action (beyond embedding the _third party service provider_.)
7. Whenever possible, the measurement APIs _should_ utilize reasonable defaults but _may_ allow for more precise configuration. 
    4. Sites that rely on defaults _should not_ receive significantly less utility from the API.


## Key Issue: Privacy Budget Management

Currently, all the proposed measurement APIs utilize some form of a _privacy budget_, which determines how differentially private noise is applied to outputs of the API. Utilization of the API deducts from that budget over the course of an epoch, and if fully consumed, the API cannot be used until the next epoch. In order to achieve goal #&#x2060;3, this budget needs to constrain the usage across all _third party service providers_, which implies that the budget must somehow be allocated between them. This allocation presents a particularly complex set of trade offs between these goals.

For example, if the API allows the budget to be consumed arbitrarily at each invocation, the first invocation may consumer the entire budget, conflicting with goal #&#x2060;5. Conversely, we could require top-level site owners to assign portions of their budget to each _third party service provider_, however this conflicts with goal #&#x2060;6. We could additionally add a default and assume that most sites will use N _third party service providers_, and by default assign each with 1/N of the budget (unless otherwise configured.) Deciding on a value for N is non-trivial: too large an N and we conflict with goal #&#x2060;7a; too small and we conflict with goal #&#x2060;2.

**Comment by eriktaubeneck** [comment]
The original issue also called out two other related items:



1. Can multiple third parties measure the same event with no restrictions?
2. Can multiple third parties measure the same event with restrictions?

From a privacy standpoint, if the budget management issue can be addressed, then there shouldn’t be an issue with measuring events multiple times (within the bounds of the global budget.) From an ad tech perspective, there may be some concerns around one _third party service provider_ not being able to measure an ad in an iFrame placed by a separate _third party service provider_. 

It would be great to hear from others about their concerns on these specific items.

**Comment by csharrison** [comment]
I think it would be productive to go through the goals and their implications, and see if we can get alignment on them (or a subset of them). There are some very nuanced privacy / utility / security tradeoffs here that you outlined very well. Thanks.

**Comment by eriktaubeneck** [comment]
I opened a PR with this content (as a draft) so that it's easier for folks to add suggestions.

**Comment by martinthomson** [comment]
To further the discussion we just had, I think that we should avoid must/should/may here and instead frame things as desirable or not.

A suggestion for the disclaimer:

> We understand that some of these goals are in tension.  Any solution will likely have to balance concerns or offer sites options that allow them to select how things like privacy budgets are allocated.  A final solution can use these goals as a way of describing its capabilities, which might include options for sites to shift any balance to suit their needs.

**Comment by AramZS** [comment]
(Noting that we will resolve this issue on the associated PR before our next meeting)

**Comment by eriktaubeneck** [comment]
@martinthomson point taken, and I'm all ears if you have a suggestion for a different modal verb that's easy to swap out. 

I did update the text in [the PR](https://github.com/patcg/docs-and-reports/pull/57) to replace all but one "must" with "should". (I left a "must" in #1, as I _think_ we have pretty strong consensus that it must be possible to delegate.)

**Comment by eriktaubeneck** [comment]
@AramZS, can we close this issue, point to the PR, and open a new issue for the next meeting if required?

**Comment by AramZS** [comment]
This [PR](https://github.com/patcg/docs-and-reports/pull/57) should close this issue for now.
