### ISSUE TITLE
Agenda Request -  Discuss Steel man process and progress comparing proposals

### ISSUE THREAD

**Issue by AramZS** [patcg/meetings#152]
## Agenda+: 

Discuss the state of steel man comparisons between proposals to progress considerations of proposals and their similarities. 

Would love it if proposal editors could contribute more details here on how they want this to go.

**Comment by AramZS** [comment]
@eriktaubeneck You had take the lead on this earlier, do you have anything specific to report yet?

**Comment by eriktaubeneck** [comment]
Unfortunately we haven't made progress since TPAC, but I'm hopeful we can make some progress during this agenda item. We can also use that time to schedule a 1 off call between interested folks to continue progress. I'm happy to lead this part of the meeting.

**Comment by AramZS** [comment]
Great, we've got a pretty loose schedule on day 2 so we can def do both.

**Comment by bmcase** [comment]
There hasn't been progress updating the comparison doc to a steelman version, though there's a [doc ](https://docs.google.com/document/d/127HgUw8j5G59zOd0PmMZNXmhIETXHPu_Ub0_JIv0YV8/edit) started for that.  But there has been some other progress since TPAC, and I can summarize where I think we are.  My understanding is that at TPAC there was alignment that the on-device/off-device decision was the biggest difference between proposals and that maybe there could be convergence between on-device proposals.  I can't speak for those proposals, but I don't think that convergence has come so far, though there has been discussion about it in the PAM ad hoc call and issues on PAM. 

The biggest ask out of these discussions -- as I understand it -- is from @csharrison about added functionality to PAM for supporting a use case that needs a very large number of ad ids to be used in creating the PAM advertiser reports.  I opened an [issue ](https://github.com/patcg-individual-drafts/private-ad-measurement/issues/9#issue-1963531388)on PAM to try and capture my understanding of the problem and clarifying questions and an idea for how PAM might support it.
