### ISSUE TITLE
Agenda Request -  PARAKEET / MaCAW / Masked LARK adoption in Chrome

### ISSUE THREAD

**Issue by drpaulfarrow** [patcg/meetings#16]
## Agenda+: PARAKEET / MaCAW / Masked LARK adoption in Chrome

Chrome is moving forwards with the origin trial for FLEDGE, however some ad tech vendors currently favour other approaches to retargeting; namely PARAKEET / MaCAW.

We would like to understand how Chrome are thinking about the testing/implementation of PARAKEET/MaCAW in the Chrome browser and whether there are any specific barriers to its adoption remaining that the ad tech community would need to address.

PARAKEET proposal: https://github.com/WICG/privacy-preserving-ads/blob/main/Parakeet.md 
MaCAW: https://github.com/WICG/privacy-preserving-ads/blob/main/MACAW.md
Masked LARK: https://github.com/WICG/privacy-preserving-ads/blob/main/MaskedLARK.md

**Comment by AramZS** [comment]
With an eye towards https://github.com/patcg/proposals/issues/4 now being in our proposals queue, think that private targeting is a topic we may want to bring up and discuss in a separate event. I'm setting aside time in the upcoming meeting to set the following meeting, including topics specifically around PARAKEET/MaCAW/Topics API. That should also give proposal authors who have not already engaged with PATCG the opportunity to do so and then we can set them up with a more extensive discussion. It looks like Masked LARK fits it with our current set of talks for the upcoming meeting though.

**Comment by alextcone** [comment]
I wouldn’t categorize Topics with PARAKEET and MaCAW. The first, Topics, is the browser acting proactively to create segments. The two Microsoft proposals mentioned are utilities for API consumers to chose their own paths. PARAKEET and MaCAW are more closely related to FLEDGE.

**Comment by lukwlodarczyk** [comment]
I think it would be useful to extend this item and hear from MS Edge - what are their plans on supporting FLEDGE Origin Trials?

**Comment by AramZS** [comment]
@lukwlodarczyk While I'm also interested in that question, I think the Web Advertising Business group might be a better place for that discussion.

**Comment by lukwlodarczyk** [comment]
@AramZS it is not clear to me how we should split questions between PATCG and Web-Adv.
Why question about PARAKEET / MaCAW / Masked LARK adoption in Chrome for Chrome may stay in PATCG?
And why mirroring question about FOT for FLEDGE need to be moved to Web-Adv?
Please advice.

**Comment by erik-anderson** [comment]
Hi everyone,

Thanks for the expression of interest here.

As Aram mentioned, we are already bringing Masked LARK into the discussion happening this week about privacy-preserving aggregation and measurement.

Our general intent is to bring privacy-preserving proposals for ad serving to this group as well for broader discussion and to hopefully get increased alignment on approach between different user agents.

I don't necessarily expect any browser vendor at this stage to accept or reject any given proposal wholesale, but it will be very beneficial to discuss desired threat models, acceptable architectures, and other pros and cons.

We're still in the process of iterating on our proposal and getting more concrete datapoints from test deployments to help inform such a discussion about the properties and strengths of privacy claims. We'd also like to observe how the measurement-related discussions evolve to make sure we appropriately seed the discussion on ad serving proposals, which is why we're initially focusing on that area.

Thanks!

**Comment by bmayd** [comment]
> Do you think these proposals are so different from Topics that they'd need an entirely different context for discussion?

I consider FLEDGE and PARAKEET to be relatively full-featured frameworks which support key aspects of ad retargeting, but don't supply targeting signals in themselves. Topics, on the other hand, is focused entirely on providing an aboutness signal for the user to the ecosystem. So, I think it makes sense to put them in separate categories.

**Comment by michaelkleber** [comment]
I agree with everything @erik-anderson said above: 
1. Privacy-preserving proposals for ad serving certainly seem like they ought to go to this group;
2. We are happy to have discussions here about threat models and architectures; and
3. Between the measurement and already-proposed Topics API, there is plenty for this group to cut its teeth on before we try to take up the big-guns ads serving work.

**Comment by AramZS** [comment]
At this time, unless someone feels strongly, it seems we still have more to focus on before picking up this topic? I will continue to leave it at agenda+next until I hear someone calling to pick it back up.
