### ISSUE TITLE
Agenda Request -  IAB Tech Lab Privacy Sandbox Q&A

### ISSUE THREAD

**Issue by AramZS** [patcg/meetings#167]
## Agenda+: What do you want to discuss?

The IAB Tech Lab put together a fit assessment around Privacy Sandbox requirements that they released to the public recently. This included a number of concerns around measurement that I thought would be useful to discuss for this group and I've invited them to answer questions from the group. I'm setting up a time on day 2 to allow them to show the report, explain the process and answer questions from the CG relevant to our work. 

## Time

30m

### Links

[Report](https://iabtechlab.com/privacysandbox/)

**Comment by AramZS** [comment]
Added to the Agenda

**Comment by martinthomson** [comment]
The [PDF of the report](https://iabtechlab.com/wp-content/uploads/2024/02/Privacy-Sandbox-Fit-Gap-Analysis-PUBLIC-COMMENT-RELEASE.pdf) might be a more useful link.  Google have also provided a [response](https://docs.google.com/document/d/10608Tp57alonCiBN9D2-0UfV_C6FFLsV5nh6sBaA5rA/preview?__s=ek7glnvk3e0k2iq1ig0f) that might contain useful corrections.

In looking into this, the report primarily concentrates on Protected Audience, so while there are concerns about attribution, they are buried.  The section on reporting includes things like reach and frequency.  The first direct discussion of attribution starts on page 50, so I recommend starting there.

My takeaways:
* Because this is primarily about Protected Audience, the attribution reporting stuff is a little garbled.
* This only talks about event-level and summary reports in ARA.
* Delays are undesirable.
* Noise is undesirable.
* Rounding/quantization is undesirable.
* Cross-device attribution is desirable.
* Multi-touch attribution is desirable.
* App-to-web attribution is desirable.
* Anti-fraud mitigations are desirable.

**Comment by therevoltingx** [comment]
Here's the link to the presentation we want to show: https://docs.google.com/presentation/d/1eeEsMxQgWFjUcv4DwD9OUZmosM74_IESl6b25gj_i2M/edit?usp=sharing
