### ISSUE TITLE
January 2022 Meeting

### ISSUE THREAD

**Issue by seanturner** [patcg/meetings#5]
# Doodle Poll

Please fill out this [link to indicate your availability](https://doodle.com/poll/i6ar3twb6g8z4w5s?utm_source=poll&utm_medium=link)

### original post follows:
Aram and I would like to suggest that the patcg have a virtual meeting in the 3rd or 4th weeks of January, most likely the 4th. The purpose of the meeting is to discuss the proposals that we know are out there. Neither of us think that an hour is sufficient and trying to prioritize the proposals for a series of hour long weekly/bi-weekly meetings seems like it might invite unnecessarily angst. Also, to provide actual discussion time we are thinking 3 hours over two days is probably what we need at a minimum. In terms of when during the day, there are no good times for this group being that we have participants in US East and West coasts, Australia, and Singapore and we probably need to expect some from Central Europe so we are proposing the meeting start at 2300 CET / 2200 UTC / 1700 EST / 1400 PST / 0600 Singapore (next day) / 0900 AEDT (next day).

We are hoping that the following day combinations might work starting at the times noted above for 3 hours:

- 18 & 19 January
- 24 & 25 January
- 25 & 26 January
- 26 & 27 January

**Comment by brodrigu** [comment]
The only dates that would work for me would be the 18 & 19.

**Comment by anderagakura** [comment]
I might not be the only one from Europe (Western Europe in my case) interested in this meeting. In case of absence, I guess you will put the recap here to follow and react, right?

**Comment by fbastello** [comment]
I'm also based in Europe (London) and the time-slot is a little challenging but understand the need to compromise if a lot of people based in Asia are interested in attending.

**Comment by peligio** [comment]
I'm also interested in attending from Europe (Western Europe) and this timing is going make it a challenge to join live. What options will we have to access the meeting/content?

**Comment by lukwlodarczyk** [comment]
I would appreciate more friendly timing for Europe to have a chance to join live or consider doing recordings.

**Comment by bmayd** [comment]
The issue title should be changed from January _2021_ to to January _2022_.

I agree with others that the timing of the meeting is going to be challenging and would prefer we bias it to include the most interested parties rather than the most regions.

If we're going to do longer meetings with agendas covering multiple topics, I suggest we include strict time-boxing which we ask everyone to respect and the chairs to enforce. In addition, I suggest we explicitly identify a process for voting to continue discussions in the event the time allotted them during the larger meeting is insufficient, as well as options for extending the discussion (e.g. chat group, email, shared document or subgroup meeting).

**Comment by seanturner** [comment]
@bmayd thanks and updated.

**Comment by npdoty** [comment]
I believe I can make any of those dates work. 

If we're looking at 6 hours of meeting time, can we start generating an agenda now? I'm not sure yet which proposals we're discussing.

**Comment by martinthomson** [comment]
I can make all of these.  Though January 25 (26 my time) is a public holiday, that's not a deal-breaker.

There isn't a whole lot of time between now and these six hours of meetings.  Do the chairs have an agenda in mind?  (I have some topics that I'd like to go through.)

**Comment by ekr** [comment]
18/19 is hard for me. The other days are much better. I also think it would be better to have it further out to give a little prep time. As MT says, this is quite soon.

**Comment by bedfordsean** [comment]
I can make all of these dates work, but am also in London so repeated late nights do not work well. Agreed we need to work on an agenda now though - this is only 2-3 weeks away

**Comment by ShivanKaul** [comment]
+1 for pushing it out a bit. I have a conflict on 25th at that time, but the rest of the days work well.

**Comment by seanturner** [comment]
To address the comments raised:

## Shifting later

I am entirely open to shifting the meeting out into end of January / beginning of February to allow more time to prepare. Is one more week or two needed? How about (and for those in the next day timezones these days are +1):

- 31 Jan & 1 Feb
- 1 & 2 Feb
- 2 & 3 Feb
- 7 & 8 Feb
- 9 & 10 Feb

## Time of day

There are interested parties in all of the time zones we chose. There is really no ideal time and I am sure that no matter what time we pick there will be request to move it.  I am not proposing that all meetings will happen at this time, I suspect we should adopt a compromise position and make it painful for everyone at some time and rotate the times.

## Time management

This is the chairs' responsibility, but we will certainly ask everyone to be mindful of the allocated time. If discussions are going long, the chairs will cut the conversation short. I do not believe that a voting mechanism is needed to continue discussion, there are plenty of mechanisms for that as was noted. If something is determined to be in scope and adopted, we will figure out a way to discuss it.

# Meeting Minutes

All patcg meetings are minuted. All of our minutes will end up in the meetings repo for that meeting. The meetings repo is [here](https://github.com/patcg/meetings). The minutes will also get posted to the mailing list.

## Agenda

Not sure if there is a standard, but I hoping to use this issue to develop the agenda. We need to address our current deliverable [Privacy Principles for Web Advertising Features](https://patcg.github.io/charter.html#work). We also need to give air time to some of the proposals that are out there; we have already received two "do we fit in patcg" requests and I am sure there are more. In other words, the agenda is pretty wide open and we are accepting agenda topics. Please kindly keep the [scope](https://patcg.github.io/charter.html#scope) in mind.

**Comment by bmayd** [comment]
> This is the chairs' responsibility, but we will certainly ask everyone to be mindful of the allocated time.

Apologize for lack of clarity, my principal suggestion is that we explicitly allocate time for topics in the agenda to help set expectations and keep us focused.

> I do not believe that a voting mechanism is needed to continue discussion, there are plenty of mechanisms for that as was noted.

Again, apologize for a lack of clarity and my poor choice of the word 'voting'. What I meant to get at is that folks are more likely to curtail discussion if it is clear how to continue it out of band; if we can take some time to figure out how that happens, then folks could quickly nominate and agree on an alternate venue to continue a discussion. I assume we'll end up with some combination of things like Slack, shared documents and GitHub issues, but think there is value in deciding what the options are ahead of time and I assume we're all doing enough virtual collaboration at this point that we'll be able to identify a couple options fairly painlessly.

**Comment by bmayd** [comment]
I don't know whether it is an appropriate agenda item, but think it would be very helpful to clarify what is meant by "advertising", particularly for deciding things like whether or not use-cases are in scope. Something like: "Advertising is the delivery to a consumer of a message paid for by a sender relating to a product or service."

**Comment by dmarti** [comment]
Good point, @bmayd. A definition of advertising doesn't need to be exact, but can be most productive if it clearly excludes related concepts such as robocalling and content marketing.

It would be helpful to qualify the definition to limit it to a communication that funds some kind of resource for its audience (not necessarily information goods, could be a bus bench). Otherwise every cold call qualifies as an advertisement. Would also mean we get to exclude junk faxes, windshield flyers, and the Internet versions of them.

Some information resources about products are [paid for by a product seller, but stand alone](https://www.kingarthurbaking.com/learn). A definition of advertising has to include some level of interruption of or attachment to the associated resource in order to not include content marketing and related areas like product documentation.

And some advertising is b2b, so would not reach a person in their role as consumer, but in their role as a business decision maker.

**Comment by martinthomson** [comment]
I have fairly hard conflicts on the first hour for the 1st and 3rd, which might rule out the first three options (if Enigma isn't enough cause).  I can make the other times work.

As for agenda, I would hope that we don't spend a whole lot of time on such esoteric topics as "what is advertising".  I was hoping that we could avoid spending a lot of time on the principles work until we had good reason to do so.  That is, use the document to record decisions on principles we need for more concrete work items.

To that end, my goal would be to spend some time on discussing whether we should work on [attribution or conversion measurement](https://github.com/patcg/proposals/issues/1) and what sort of constraints we might set for that work.  That necessarily means addressing a number of principled questions.  For example, we might need to decide whether we believe that attribution information should be provided on a per-event basis or only in the aggregate.

I've a longer list that I'm happy to talk through if it comes to that.  I also have opinions on what I think the answers should be for many of those.

**Comment by alextcone** [comment]
I strongly agree @martinthomson.

> As for agenda, I would hope that we don't spend a whole lot of time on such esoteric topics as "what is advertising"

**Comment by eriktaubeneck** [comment]
@seanturner and @AramZS, may I suggest starting a poll and encouraging folks to provide their availability so that we can lock down a date in the near future. [Doodle](https://doodle.com/create) is a free tool for this type of scheduling, and I've seen used in other W3C groups.

I personally have limited availability in the first weeks of February (particularly the second), and to some extent my vacation timing was aimed for after the original dates proposed here. Certainly this group will not be able to meet everyones needs, but it would be great if we could have a date set so that folks can plan around it as needed.

**Comment by seanturner** [comment]
I have update the first post in this issue to include a doodle poll for dates. Please indicate your availability. Actually, here's the same [link](https://doodle.com/poll/i6ar3twb6g8z4w5s?utm_source=poll&utm_medium=link) in case people only get the new posts.

**Comment by drpaulfarrow** [comment]
I would be a strong advocate for meetings being at EMEA-friendly times, given the level of participation from EMEA representatives up to this point and the expertise EMEA has gained through the creation and implementation of GDPR, ePrivacy and TCF, for example. I think EMEA's experience and engagement is invaluable.

Could we put the meeting time to a vote?

**Comment by ekr** [comment]
We should not vote. There are a large number of potential meeting times and the chairs should try to balance out the various options using their best judgement.

On the merits of the situation, we *also* have to have APAC-friendly times and usually that requires a time that isn't perfect for either EMEA or APAC.

**Comment by eriktaubeneck** [comment]
> We should not vote.
+1. To be clear, my suggestion for a poll above was just to gather more information for the chairs to perform that balancing act. I trust their judgement (even if the timing is difficult for me personally.)

**Comment by jdelhommeau** [comment]
in that case, and because there is already a poll for days we can meet, couldn't we provide choices for same days at different time? That way, each interested participant can provide his time and day of choice, and then chairs can perform that balancing act. Current time in the Doodle are all non EMEA friendly.

**Comment by drpaulfarrow** [comment]
I take that point, 100%. 

So, we will have some meeting times which are unfriendly for EMEA, some for APAC and some for the US? That makes sense.

**Comment by anderagakura** [comment]
+1 @darobin We will all face this issue. The good thing is a lot of people around the world want to join this meeting. Could we make sure the meetings are recorded and/or note are taken?

**Comment by drpaulfarrow** [comment]
Recordings would be great!

**Comment by npdoty** [comment]
-1 for recordings: I can live with it if necessary (although probably with my video mostly turned off), but I think it discourages candid conversation and adds a privacy cost to participating.

But chairs have noted already that all meetings will be minuted and the notes distributed afterwards. In my experience, it's often faster and more effective for me to catch up on the contents of a conversation that I missed via good W3C-style notes than it would be to watch an entire recording.

**Comment by ekr** [comment]
I also am not a huge fan of being recorded, especially when I go back and watch myself, but I think that we should do so nevertheless because it's part of having a transparent standards process.

**Comment by michaelkleber** [comment]
The [W3C Process](https://www.w3.org/Consortium/Process/Drafts/#meeting-recording) is that meetings can only be recorded if everyone involved agrees.  Both the Web-Adv BG and the FLEDGE WICG meetings had the whether-to-record discussions, and all ended up _not_ recording interactive discussion (though sometimes recording prepared presentations and stopping at Q&A time).

Of course this isn't a guarantee of what will happen if the question is raised for this CG, but there is enough overlapping membership that it's not a bad guess.

**Comment by martinthomson** [comment]
Can we perhaps spin off a new issue for the recordings discussion?

**Comment by drpaulfarrow** [comment]
My experience of the notes from other W3C meetings (and indeed most meetings) is that they are often quite difficult to read and not a great substitute for attendance, given the complexity and nuance inherent within the subject matter. I totally appreciate people's reservations about being recorded (I don't like it either), but given that some very engaged folks will be excluded from these meetings due to timezone constraints, I would hope that consensus could be achieved.

**Comment by appascoe** [comment]
I'm with Nick. I'm not a fan of being recorded and having that be publicly available. In addition, I find that I can scour the notes much more effectively, including links to additional documentation, than being forced to linearly go through a video. Since we're talking about a couple three-hour meetings, I'd much prefer notes to refer to.

If something is unclear, asking a question in Github seems to be the most effective way of getting an answer and furthering conversation.

**Comment by eriktaubeneck** [comment]
I opened a new issue to discuss this: #10. Please move future discussion there. cc: @anderagakura @drpaulfarrow @npdoty @ekr @michaelkleber @appascoe, in case you'd like to include your existing comments in that thread.

**Comment by seanturner** [comment]
Thanks to all that participated in the doodle poll (all 35 of you). The best two consecutive days are Feb 9 and 10.  Mark your calendars now. We will get the ball rolling to have the meeting officially announced.

**Comment by AramZS** [comment]
Times and dates have been set for this upcoming meeting. I have added them to the agenda file at https://github.com/patcg/meetings/tree/main/2022/02/09-telecon which means this issue is officially resolved. I'm leaving it open for now so that people who check the issues for the dates can see it here as well, but please do not add anything additional to this thread, instead adding or adding to agenda items.

**Comment by seanturner** [comment]
Pleas note that I have updated the w3c's patcg calendar to reflect the meeting times as well as to include the webex link:
https://www.w3.org/groups/cg/patcg/calendar
